##############################################################################
# Gemfile (and Gemfile.lock)
#
#  This file contains the Ruby gem manifest for Middlemac's dependencies.
#
#  To ensure that the correct gems are installed, do `bundle install`.
#
#  Note that Gemfile.lock is under version control; `bundle install` will
#  ensure that the correct gem versions are used when this repository is
#  checked out. To update to newer gems and update Gemfile.lock, use
#  `bundle update`.
##############################################################################

source 'https://rubygems.org'


#######################################
# Middlemac, natch.
#######################################
gem 'middlemac', '~> 3.1.1'
gem 'middleman-targets', '~> 1.0.12'


#######################################
# Core gems
#######################################
gem 'middleman', '~> 4.3.7'
gem 'middleman-core'
gem 'middleman-cli'
gem 'middleman-livereload' # Live-reloading plugin
gem 'middleman-syntax'     # Syntax Highlighting
gem 'middleman-compass'


#######################################
# Other gems
#######################################
gem 'tzinfo-data', platforms: [:mswin, :mingw] # Time zone data for Windows
